name: search-engine-automation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - requests
  - matplotlib
  - numpy
  - pip
  - pip:
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
